### ISSUE TITLE
Unable to deploy

### ISSUE THREAD

**Issue by kuabhish** [aws-samples/eb-node-express-sample#18]
I am following https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/nodejs-dynamodb-tutorial.html

and so I downloaded the zip of this repo and was trying to deploy it.

But I aam getting the following error all the time:
```

Invalid option specification (Namespace: 'aws:elasticbeanstalk:container:nodejs:staticfiles', OptionName: '/static'): Unknown configuration setting.

```

How can I solve it?

**Comment by tajerramt** [comment]
-First of all, I think you guys should download this link:
https://github.com/aws-samples/eb-node-express-signup
-Then unzip the file.
-Then enter the file and zip all elements inside the file(Dont zip the entire folder(root), you should only zip the files inside it
)
-Then deploy it

**Comment by sveinhov** [comment]
I'm having the same problem. kuabhish, were you able to resolve this?

**Comment by kuabhish** [comment]
Sorry @sveinhov i didn’t move forward with it. I stopped actually. I am stuck with the development work now. After I finish it I will try it again.

**Comment by laggleton** [comment]
Found the issue - it doesn't work with the default Linux version https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/command-options-specific.html#command-options-nodejs

Solution: When you create the application and choose the Platform as 'Node.js' you then need to select the Platform branch as 'Node.js running on 64bit Amazon Linux' - don't choose any of the 'Linux 2' options. Then it should be deployable.

**Comment by eavestn** [comment]
> -First of all, I think you guys should download this link:
> https://github.com/aws-samples/eb-node-express-signup
> -Then unzip the file.
> -Then enter the file and zip all elements inside the file(Dont zip the entire folder(root), you should only zip the files inside it
> )
> -Then deploy it

Don't do this. That repo is seven years old.

**Comment by geoseong** [comment]
I have problem related this.

I've changed `container:nodejs:staticfiles -> environment:proxy:staticfiles` configuration but `eb` command still return this error
```
ERROR: ServiceError - Configuration validation exception: Invalid option specification (Namespace: 'aws:elasticbeanstalk:container:nodejs:staticfiles', OptionName: '/static'): Unknown configuration setting.
```

here are my configurations file.

### git
```
[credential]
	helper = !aws --profile {my-aws-profilename} codecommit credential-helper $@
	UserHttpPath = true
```

### .ebextensions/options.config
```
option_settings:
  aws:elasticbeanstalk:customoption:
    NewSignupEmail: me@example.com
  aws:elasticbeanstalk:application:environment:
    THEME: "flatly"
    AWS_REGION: '`{"Ref" : "AWS::Region"}`'
    STARTUP_SIGNUP_TABLE: '`{"Ref" : "StartupSignupsTable"}`'
    NEW_SIGNUP_TOPIC: '`{"Ref" : "NewSignupTopic"}`'
  aws:elasticbeanstalk:environment:proxy:
    ProxyServer: nginx
  aws:elasticbeanstalk:environment:proxy:staticfiles:
    /static: /static
```

### .elasticbeanstalk/config.yml
```yml
branch-defaults:
  master:
    environment: null
    group_suffix: null
global:
  application_name: ebstudy200928
  branch: master
  default_ec2_keyname: eb-study-200928
  default_platform: Node.js 12 running on 64bit Amazon Linux 2
  default_region: ap-northeast-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: {my-aws-profilename}
  repository: eb-study-200928
  sc: git
  workspace_type: Application
```

Checking in my ElasticBeanstalk Console, there is only "Application" named `ebstudy200928`. there's no "Environment" existed.
